spring:
  datasource:
    url: jdbc:mysql://localhost:3306/query_service
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

grpc:
  server:
    port: 9090
